### ISSUE TITLE
Where will new metadata records go?

### ISSUE THREAD

**Issue by Br-Johnson** [international-year-of-the-salmon/about#1]
Catalogue is now live at data.npafc.org. Need to test where the forms go when they are created with the CIOOS metadata intake form...

**Comment by timvdstap** [comment]
Interestingly enough, doesn't seem to be showing up on either catalogue....

**Comment by timvdstap** [comment]
Issue on not showing up in either catalogue is resolved. New metadata records currently go to both the iys.hakai.org and data.npafc.org catalogues.
